on:
  push:
    branches:
      - master
      - '0.[0-9]+.x'
      - '1.[0-9]+.x'

name: Publish Docs
jobs:
  publish_docs:
    if: github.repository == 'diesel-rs/diesel'
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-doc-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Get the branch name
      id: current_branch
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libmysqlclient-dev libsqlite3-dev libpq-dev
    - name: Build documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --manifest-path diesel/Cargo.toml --features "postgres sqlite mysql extras" --workspace

    - name: Publish documentation
      if: success()
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target/doc # The folder the action should deploy.
        # Store documentation for each branch in a different folder
        # This allows us to differentiate between docs for master
        # and docs for already released versions
        TARGET_FOLDER: ${{ steps.current_branch.outputs.branch }}
