#!/bin/sh

set -e

BINARY=target/arm-unknown-linux-gnueabi/release/iotnode
cargo build --release --target arm-unknown-linux-gnueabihf
arm-linux-gnueabihf-strip "$BINARY"
rsync -av "$BINARY" pi@192.168.86.36:
